 
INSERT INTO CIB_DICTIONARY_KEYS (KEY_NAME,KEY_DESCRIPTION,TOOLTIP,KEY_TYPE) VALUES('KeyName1','KeyDescription1','TooltipKey1','KeyType1'); 
INSERT INTO CIB_DICTIONARY_KEYS (KEY_NAME,KEY_DESCRIPTION,TOOLTIP,KEY_TYPE) VALUES('KeyName2','KeyDescription2','TooltipKey2','KeyType2'); 
INSERT INTO CIB_DICTIONARY_KEYS (KEY_NAME,KEY_DESCRIPTION,TOOLTIP,KEY_TYPE) VALUES('KeyName3','KeyDescription3','TooltipKey3','KeyType3'); 
INSERT INTO CIB_DICTIONARY_KEYS (KEY_NAME,KEY_DESCRIPTION,TOOLTIP,KEY_TYPE) VALUES('KeyName4','KeyDescription4','TooltipKey4','KeyType4');
 
INSERT INTO CIB_DICTIONARY (KEY_NAME,LANGUAGE_CODE,KEY_VALUE) VALUES('KeyName1','GE','KeyValue1'); 
INSERT INTO CIB_DICTIONARY (KEY_NAME,LANGUAGE_CODE,KEY_VALUE) VALUES('KeyName2','EN','KeyValue2'); 
INSERT INTO CIB_DICTIONARY (KEY_NAME,LANGUAGE_CODE,KEY_VALUE) VALUES('KeyName3','TR','KeyValue3'); 
INSERT INTO CIB_DICTIONARY (KEY_NAME,LANGUAGE_CODE,KEY_VALUE) VALUES('KeyName4','RU','KeyValue4');